- TCutility/__init__.py
- TCutility/results/adf.py
- TCutility/results/ams.py
> 13 error when reading calculations on single atoms

- TCutility/results/result.py
Finished issue #22. Result class now works case-insensitive and was simplified a lot
> 22 simplify the result object and add case insensitivity

- TCutility/results/adf.py
- TCutility/results/dftb.py
In some places we were still manually parsing the input files, now we should be exclusively using our own input parser function
> Now reading task from input from input parser

- TCutility/molecule.py
- test/fixtures/xyz/transitionstate_radical_addition.xyz
- test/test_molecules.py
Finished issue #37 . I copied over the molecule.py from yutility and improved its readability and generalizability.
> 37 support for custom xyz files

- src/tcutility/results/adf.py
> Added the case of ioprel eq 0

- src/tcutility/__init__.py
We were missing an import of the data module leading to import errors
> Fixed missing import of tcutility.data

- src/tcutility/job/ams.py
The ModeToFollow key was in the wrong section
> Fixed an issue with modetofollow in TS search

- src/tcutility/job/adf.py
> Added the symmetry method to ADFJob

- src/tcutility/results/ams.py
> Running job fatal status is set to False

- src/tcutility/pathfunc.py
Reverts TheoChem-VU/TCutility#158
There are some issues with the new functionality
> Revert "Added support for matching files"

- src/tcutility/log.py
It currently looks like this.
https://github.com/TheoChem-VU/TCutility/assets/42876712/5b05a3ab-3412-47da-95fa-d23d91499eab
> Added support for generator expressions for loadbar

- src/tcutility/results/ams.py
We now read some useful properties of PES scan results
> We now read some PESScan properties

- src/tcutility/results/adf.py
Added property for energy.orbint.correction
> Added  energy.orbint.correction

- src/tcutility/geometry.py
I made some improvements to the `Transform` class, it now works as it should and there is some new functionality.
- #293 
- #294 
- #295
> Made improvements to the `tcutility.geometry.Transform` classes

- src/tcutility/formula.py
There was an issue with the generation of molecular formulae for LaTeX and pyplot rendering engines (see #318).
> Fixed an issue with wrongly generated LaTeX and pyplot molecular formulae

- src/tcutility/job/adf.py
Left some typo's in the `ADFFragmentJob` definition which was causing some issues
> Fixed a typo causing crashes in `ADFFragmentJob`

- src/tcutility/molecule.py
* We added dosctrings to a few functions in the `tcutility.molecule` module
* Added the new `charge` kwarg to the `tcutility.molecule.number_of_electrons` function
* Turned the `tcutility.molecule.parse_str` function into a private function
> Improvements to the `tcutility.molecule` module

- src/tcutility/pathfunc.py
- test/test_pathfunc.py
The new function allows you to calculate the 'depth' of a given path.
> Added the `tcutility.pathfunc.path_depth` function

- src/tcutility/cite.py
Fixed an issue where sometimes reading pages and volume of a citation would fail.
> Fixes to the `tc cite` program

- src/tcutility/job/generic.py
This should fix some issues related to job submission
> Switched the default `afterok` dependency setting to `afterany`

- src/tcutility/job/adf.py
- src/tcutility/job/generic.py
- src/tcutility/job/workflow.py
Added dependencies and fixed use_slurm=False for ADFFragmentJob
> 413 add dependencies on other slurm jobs to workflows

- src/tcutility/connect.py
- src/tcutility/job/generic.py
We had some issues with e.g. squeue calls not working properly on Snellius. This PR should hopefully fix this issue for all systems.
> Some subprocess calls were not properly handled on some systems

- src/tcutility/job/adf.py
We can now overwrite outputs for `DensfJob` calculations
> Added the `overwrite` argument for `DensfJob` calculations
