TheoChem-VU/TCutility

TCutility/results/adf.py
We are now retrieving Gibb's free energy and enthalpy
=> Reading of thermodynamic data

TCutility/__init__.py, TCutility/formula.py, TCutility/report.py, examples/write_SI.py, test/test_formula.py
We can now write coordinates and information about calculations to a Word document using the new `TCutility.report.SI` class. Also added parsing of chemical formulas for HTML and LaTeX rendering.
=> Automatic writing of coordinates to si files

src/tcutility/log.py
I tried to add some tests for this, but it does not seem possible to do this easily with pytest.
=> Added the caller_level argument for some of the logging functions.

src/tcutility/job/adf.py
We have deprecated the ADFJob.SCF_convergence method in favor of the ADFJob.SCF method. Also added the iterations argument to ADFJob.SCF for setting the number of SCF iterations. This was needed for PyOrb.
=> 115 deprecate adfjobscf convergence

src/tcutility/job/ams.py
Added support for uniform electric fields
=> Added the electric_field method for AMSJob classes

src/tcutility/job/adf.py, src/tcutility/job/generic.py
Jobs now do not run if an exception occured in its setup, but will not crash the program.
=> 184 do not run a calculation if its set up failed

src/tcutility/results/adf.py, test/test_adf_properties.py
Added reading of the properties as well as some tests
=> 193 read the s2 operator expectation value and spin contamination for adf calculations

src/tcutility/job/adf.py, src/tcutility/job/ams.py, src/tcutility/job/generic.py, src/tcutility/results/result.py
This now works, but we should add some test-cases
=> 183 add job inheriting

src/tcutility/data/functionals.py
This now works. Path safe names can now be used to get functional info. Wrong keys will now give errors.
=> We can now get functional info by the path safe name

src/tcutility/job/orca.py
The settings attribute has been readded and the job should run again without problems.
=> Fixed missing settings attribute for ORCAJob

src/tcutility/log.py
This PR will add the `tcutility.log.rectangle_list` function that prints a list of string values as a rectangle that fits the shell that the user is using.
E.g.
```python
>>> from tcutility import log
>>> log.rectangle_list(range(200))
[2024/04/30 22:15:29] 0    1    2    3    4    5    6    7    8    9    10   11   12   13   14   15   16   17 
[2024/04/30 22:15:29] 18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35 
[2024/04/30 22:15:29] 36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53 
[2024/04/30 22:15:29] 54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71 
[2024/04/30 22:15:29] 72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89 …
```
=> Added tcutility.log.rectangle_list

src/tcutility/job/adf.py, src/tcutility/job/ams.py
Added a AMSJob method that is always called before the calculation is run. This is used, currently, to make sure that the initialhessian is not set to DFTB if spin-polarized ADF calculation was requested.
=> Check job pre-run function

src/tcutility/cli_scripts/geo.py, src/tcutility/cli_scripts/tcparser.py, src/tcutility/geometry.py
We added the new `tc geo` command:
```
usage: tc geo [-h] [-p] xyzfile atom_indices [atom_indices ...]
Calculate geometrical parameters for atoms at the provided indices. For 1 index this program returns the cartesian coordinate for this atom. For 2 indices return bond length
between atoms. For 3 indices return bond angle, with the second index being the central atom. For 4 indices return dihedral angle by calculating the angle between normal
vectors described by atoms at indices 1-2-3 and indices 2-3-4. If the -p/--pyramidal flag is turned on it calculates 360° - ang1 - ang2 - ang3, where ang1, ang2 and ang3 are
the angles described by indices 2-1-3, 3-1-4 and 4-1-2 respectively.
positional arguments:
xyzfile          The molecule to calculate the parameter for.
atom_indices     The …
```
=> Add geometric parameter function and the new tc geo command

src/tcutility/cite.py
The solution was to simply replace the normal dash with the correct one before formatting the citation.
=> Citation page-ranges now use the correct dash

src/tcutility/job/orca.py
I fixed an issue where the path to the input file is wrong in the runscript.
=> Fixed an issue with wrongly named input file in ORCAJob call when not using temporary directories

src/tcutility/report/__init__.py
We should now be able to use the character module.
=> Fixed an issue where the `report.character` module was not importable

src/tcutility/timer.py
In cases where a function that was tracked using the `tcutility.timer` class was not called during the runtime there would be a userwarning originating from a `numpy.mean` call. This PR fixes that.
=> Fixed a `timer` runtimewarning that occurs when a function was not called

src/tcutility/__init__.py
We were missing an import of `pathfunc` in the main `__init__.py`. This caused an error when importing it in a script.
=> `pathfunc` is now importable from `tcutility` directly

examples/job/elstat_decomp.py, src/tcutility/job/adf.py, src/tcutility/molecule.py, src/tcutility/results/adf.py, src/tcutility/results/ams.py, test/test_vdd_analysis.py
We added the option `decompose_elstat`  to the constructor of `ADFFragmentJob` class. It will perform extra calculations that allow you to obtain energy terms that constitute the electrostatic potential energy. These are the electron–electron repulsion, electron–nucleus attraction and nucleus–nucleus repulsion. This decomposition further decomposes the electron–nucleus attraction into the fragment terms. It does so by removing the electrons of one fragment and interacting it with the other fragment.
We also added the new electrostatic terms to the `Result.properties.energy.elstat` object, specifically the new `total`, `Vee`, `Ven` and `Vnn` terms.
=> Added option to perform electrostatic potential energy decomposition for `ADFFragmentJob`

src/tcutility/job/adf.py
There was a typo: `type` instead of the expected `typ` that appeared in the `ADFJob.basis_set` method. This was causing crashes and preventing the calculations from being run.
=> Fixed an issue with `ADFJob.basis_set` method causing crashes

examples/job/elstat_decomp.py, src/tcutility/__init__.py, src/tcutility/analysis/pyfrag.py, src/tcutility/cli_scripts/geo.py, src/tcutility/cli_scripts/resize_figures.py, src/tcutility/cli_scripts/tcparser.py, src/tcutility/job/adf.py, src/tcutility/molecule.py, src/tcutility/pathfunc.py, src/tcutility/report/__init__.py, src/tcutility/report/figure_resizer.py, src/tcutility/results/adf.py, src/tcutility/results/ams.py
There were some issues related to the recent implementation of the electrostatic potential decomposition analysis with `ADFFragmentJob`. This PR aims to fix those issues.
- Fixed an issue related to sbatch settings not properly being set for child jobs
- Fixed an issue where we could not access the `job` module without explicitly importing it
- Fixed a problem where the `Elstat` print option was overwriting the user-set print options
=> Fixes for electrostatic decomposition analyses

src/tcutility/data/atom.py
Previously atomic colors were returned as RGB values only. Now we can also get them as hex strings.
=> `tcutility.data.atom.color` calls can be now be given as hex strings instead of RGB only

src/tcutility/timer.py
Whenever something was registered to the timing module we printed a table at the end of the runtime, however this is not necessary if there were no calls made to the registered callables.
=> Not printing timing table if there were no calls to registered callables

src/tcutility/cli_scripts/resize_figures.py
There was an error due to us starting a tkinter session at the module level in the `tc resize` program.
=> Fixed an issue related to `tkinter` on display-less systems

examples/job/uvvis.py, src/tcutility/job/adf.py
We added the new `tcutility.ADFJob.excitations` method used to calculate electronic excitations, e.g. UV/VIS spectra. It also works with `ADFFragmentJob` calculations and will only calculate excitations for the complex.
I also added an example calculation that showcases the usage for this new method.
=> Added support for calculating electronic excitations with `ADFJob`

examples/job/uvvis.py, src/tcutility/job/adf.py
Previously, running the following script:
```python
with ADFFragmentJob() as job:
job.molecule(...)
job.unrestricted(True)
```
Would result in an error mentioning that the `UnrestrictedFragments` keyword was not set in the input file of the complex. This PR will fix this issue.
I also changed the uvvis example as a little bonus.
=> Fixed an issue where unrestrictedness was not propagated to childjobs in `ADFFragmentJob` calculations

src/tcutility/cli_scripts/geo.py, src/tcutility/geometry.py
* We can now calculate the sum of angles with the `geometry.parameter` function.
* Sum-of-angle calculations have also been added to the `tc geo` CLI program
* The `tc geo` CLI can now be provided a calculation directory instead of only a XYZ-file.
* If 0 indices are given to `tc geo` we print the whole molecule.
* General improvements to the documentation of `tc geo`
=> Added calculation of sum of angles to `geometry.parameter`

src/tcutility/pathfunc.py, test/test_pathfunc.py
In the old version of `tcutility.pathfunc` we used the `os.listdir` function which is much slower than using the `os.scandir` class. Using this new method we find speed-ups of up to 4x for the `pathfunc.match` and `pathfunc.get_subdirectories` functions.
=> Large speedups for the `tcutility.pathfunc` module

src/tcutility/__init__.py, src/tcutility/job/generic.py, src/tcutility/results/__init__.py, src/tcutility/results/orca.py
I made the job status much more efficient by simply calling the `get_calculation_status` function of the engine results modules directly instead of first loading all data and then checking the status.
Testing the following code against my radical addition benchmark calculations:
```python
import tcutility
for folder, info in tcutility.pathfunc.match('data/abinitio', '{sp}_{sub}_{rad}/{job}/{subjob}').items():
with tcutility.timer.timer('quick status'):
qs = tcutility.results.quick_status(folder).name
with tcutility.timer.timer('old status'):
os = tcutility.results.read(folder).status.name
assert qs == os
```
Results in a ~4.7x speedup
```
[2025/02/08 23:07:15] Function       Calls   Mean (s)   Time Spent (s)   Rel. Time
[2025/02/08 23:07:15] …
```
=> Made job status checking more efficient

src/tcutility/pathfunc.py
I implemented a new version of `match` using the `glob` python module. From testing the speed-ups are limited, but I think the implementation is much simpler now. From testing I find a speedup of around 1.2x:
```python
from tcutility import timer, pathfunc
for _ in range(1000):
with timer.timer('Using scandir'):
res_old = pathfunc.match('calcs_test', '{donor}-{acceptor}/{level_of_theory}')
with timer.timer('Using glob'):
res_new = pathfunc.match2('calcs_test', '{donor}-{acceptor}/{level_of_theory}')
assert sorted(res_old) == sorted(res_new)
```
yields
```
[2025/02/17 19:05:38] Function        Calls   Mean (s)   Time Spent (s)   Rel. Time
[2025/02/17 19:05:38] ──────────────────────────────────────────────────────────────
[2025/02/17 19:05:38] Using glob      1000    0.003      2.933 …
```
=> Small speed-ups for `pathfunc.match`

src/tcutility/connect.py, src/tcutility/job/ams.py, src/tcutility/job/generic.py
You can now give charges, spin-polarizations and solvents to xyz-files. These will be read before starting a calculation and added as settings to the job.
=> Added reading of system settings from extended XYZ-files

src/tcutility/connect.py
Fixed an issue related to an attribute not being present during job setup
=> Added missing `postamble_defaults` attribute to `connect.Server` classes

src/tcutility/job/ams.py
We can now specify constraints for the AMS engine to use
=> Add constraints to `AMSJob` calculations

src/tcutility/job/adf.py
We can now specify the IrrepOccupation block for ADF calculations
=> Added the `irrep_occupations` method for `ADFJob` calculations

src/tcutility/analysis/__init__.py, src/tcutility/job/adf.py
PyOrbb has deprecated an attribute of the `Orbital` objects that we used in DensfJob.
=> Fixed an issue with deprecated attributes being used

src/tcutility/job/adf.py
I have added the option to extend the grid for `DensfJob` calculations. This alows us to easily increase the size of generated grids. By default it is set to 7.5 bohr. This is also the standard for the densf calculations used by AMS in the AMSView program. #462 
Secondly there was an issue with the generation of cube files for unrestricted MOs. #463
=> Added the `grid_extend` parameter to `gridsize` method of DensfJob and fixed an issue with MOs with differing spins.
